#!/usr/bin/env bash
#
# pgp.io CLI helper

VERSION='0.1.0'
ENDPOINT='https://pgp.io/m'

while getopts ":hv" opt; do
  case $opt in
    v)
      echo "pgp.io CLI helper $VERSION"
      exit 0
      ;;
    h)
      echo "pgp.io CLI helper $VERSION"
      echo
      echo "Usage:"
      echo
      echo "  Encrypt & Send"
      echo "  echo 'hello' | gpg -aesr '<recipient>' | pgpio"
      echo
      echo "  Receive & Decrypt"
      echo "  pgpio Jag61Hgz19L | gpg -d"
      echo
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Receive
if [ $1 ]; then
  # Accept either a message ID or a full URL.
  if [ "${1:0:4}" == "http" ]; then
    url=$1
  else
    url="$ENDPOINT/$1?plain=1"
  fi

  result=`curl -sSL "$url"`
  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    echo "$result"
  fi
# Send
else
  result=`curl -sSfi --data-binary @- $ENDPOINT`
  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    location=`echo "$result" | grep Location | awk '{print $2}'`
    echo "$location"
  fi
fi

