#!/usr/bin/env bash
#
# pgp.io CLI helper

VERSION='0.1.0'
DOMAIN='https://pgp.io'

while getopts ":hv" opt; do
  case $opt in
    v)
      echo "pgp.io CLI helper $VERSION"
      exit 0
      ;;
    h)
      echo "pgp.io CLI helper $VERSION"
      echo
      echo "Usage:"
      echo
      echo " -h : This help."
      echo " -v : Return the current version."
      echo
      echo "  Encrypt & Send"
      echo "  echo 'hello' | gpg -aesr '<recipient>' | pgpio"
      echo
      echo "  Receive & Decrypt"
      echo "  pgpio Jag61Hgz19L | gpg -d"
      echo
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Receive
if [ $1 ]; then
  result=`curl -sSL "$DOMAIN/m/$1?plain=1"`
  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    echo "$result"
  fi
# Send
else
  result=`curl -sSfi --data-binary @- $DOMAIN/m/`
  RETVAL=$?

  if [ $RETVAL -eq 0 ]; then
    location=`echo "$result" | grep Location | awk '{print $2}'`
    echo "$location"
  fi
fi

